import '../styles/globals.css'
import Head from 'next/head'
import Header from '../components/header/Header'

function MyApp({ Component, pageProps }) {
  return (
    <div id='general_container' theme='dark_forest'>
      <Head>
        <title>OvDev Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Header />
      

      <main>
        <Component {...pageProps} />
      </main>

      <footer>
        footer
      </footer>

      <style jsx>{`
        div[theme="dark_forest"]{
            --dark: #041122;
            --normal-color: #259073;
            --light-color: #7FDA89;
            --very-light: #E6F99D;
            --text-color: #FEFEFE;
        }
      `}</style>

      <style jsx>{`
        div[theme="dark_ocean"]{
          --dark: #100F0F;
          --normal-color: #0F3D3E;
          --light-color: #E2DCC8;
          --very-light: #F1F1F1;
          --text-color: #FEFEFE;
        }
      `}</style>

      <style jsx>{`
      div[theme="pink_sunset"]{
          --dark: #060930;
          --normal-color: #333456;
          --light-color: #595B83;
          --very-light: #F4ABC4;
          --text-color: #FEFEFE;
      }
      `}</style>
    </div>
  )
}

export default MyApp
