import '../styles/globals.css'
import Head from 'next/head'
import Header from '../components/header/Header'
import { Provider } from 'react-redux';
import store from '../redux/store/index';
import React, { useState, useEffect } from 'react';
import Footer from '../components/footer/Footer';
import '../assets/reset.css'

function MyApp({ Component, pageProps }) {
  const [themes, setThemes] = useState([]);

  return (
    <Provider store={store}>
      <div id='general_container' theme='deep_forest' style={{color: '#F0F0F0'}}>
        <Head>
          <title>OvDev Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        
        <Header/>
        
        <Component {...pageProps} setThemes={setThemes}/>

        <Footer />
        
      </div>
    </Provider>
  )
}

export default MyApp
