import '../styles/globals.css'
import Head from 'next/head'
import Header from '../components/header/Header'
import { Provider } from 'react-redux';
import store from '../redux/store/index';
import React, { useState } from 'react';
import Footer from '../components/footer/Footer';
import '../assets/reset.css';
import { I18nextProvider } from 'react-i18next';
import i18next from 'i18next';
import global_es from '../assets/translations/es/global.json';
import global_en from '../assets/translations/en/global.json';

i18next.init({
  interpolation: {
    escapeValue: false
  },
  lng: "es",
  resources: {
    es: {
      global: global_es
    },
    en: {
      global: global_en
    }
  }
});

function MyApp({ Component, pageProps }) {
  const [themes, setThemes] = useState([]);

  return (
    <Provider store={store}>
      <I18nextProvider i18n={i18next}>
        <div id='general_container' theme='deep_forest' style={{color: '#F0F0F0'}}>
          <Head>
            <title>OvDev Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Header/>
          
          <Component {...pageProps} setThemes={setThemes}/>

          <Footer />
          
        </div>
      </I18nextProvider>
    </Provider>
  )
}

export default MyApp
